export type ShopDataType = {
	path: string;
	name: string;
	address: string;
	genre: string;
	sub_genre: Array<string>;
	photo: string;
	Recommended_number_of_people: string;
	business_hours: string;
	Regular_holiday: string;
	time_from_company: string;
};

export const Shops = (): Array<ShopDataType> => {
	return [
		{
			path: "/shop/1",
			name: "うさぎ",
			address: "東京都渋谷区神泉町8-13 アーガス霜田ビル 1F",
			genre: "麺類",
			sub_genre: ["坦々麺", "汁なし坦々麺"],
			photo: "",
			Recommended_number_of_people: "1~3人",
			business_hours: "11:30～14:30（L.O.）",
			Regular_holiday: "土曜日、日曜日、祝日",
			time_from_company: "7~10分",
		},
		{
			path: "/shop/2",
			name: "中華そば 満鶏軒 南平台店",
			address: "東京都渋谷区南平台町15-11 南平台野坂ビル 1F",
			genre: "麺類",
			sub_genre: ["油そば", "まぜそば", "つけ麺"],
			photo: "",
			Recommended_number_of_people: "1~3人",
			business_hours: "11:30～15:30(L.O.15:15)",
			Regular_holiday: "日曜・祝日（土曜日不定休）",
			time_from_company: "5~7分",
		},
		{
			path: "/shop/3",
			name: "トマトマン（THE TOMATOMAN）",
			address: "東京都目黒区青葉台3-1-18",
			genre: "麺類",
			sub_genre: ["つけ麺", "汁なし坦々麺"],
			photo: "",
			Recommended_number_of_people: "1~4人",
			business_hours: "11:30〜15:00(L.O.14:30)",
			Regular_holiday: "日曜日",
			time_from_company: "3~5分",
		},
		{
			path: "/shop/4",
			name: "龍の子 ",
			address: "東京都世田谷区池尻3-3-2",
			genre: "麺類",
			sub_genre: ["中華料理","坦々麺","食堂"],
			photo: "",
			Recommended_number_of_people: "1~4人",
			business_hours: "11:30～13:30 18:00～22:00",
			Regular_holiday: "日曜日",
			time_from_company: "8~10分",
		},
		{
			path: "/shop/5",
			name: "Oti ",
			address: "東京都目黒区青葉台3-10-11 青葉台フラッツ　2F",
			genre: "麺類",
			sub_genre: ["イタリアン", "ダイニングバー"],
			photo: "",
			Recommended_number_of_people: "1~4人",
			business_hours: "11:30～15:00（L.O.14:30）/18:00～23:00（L.O.22:00）",
			Regular_holiday: "月曜日、第２日曜日",
			time_from_company: "3~5分",
		},
		{
			path: "/shop/6",
			name: "和利道 ",
			address: "東京都目黒区青葉台3-10-11 青葉台フラッツ　2F",
			genre: "麺類",
			sub_genre: ["つけ麺", "ラーメン"],
			photo: "",
			Recommended_number_of_people: "1~3人",
			business_hours: "11:00～15:30／18:00～21:00（スープ切れ早仕舞い）",
			Regular_holiday: "水曜日",
			time_from_company: "3~5分",
		},
		{
			path: "/shop/7",
			name: "長寿庵 ",
			address: "東京都目黒区東山3-4-7",
			genre: "麺類",
			sub_genre: ["そば", "うどん", "丼"],
			photo: "",
			Recommended_number_of_people: "1~4人",
			business_hours: "11:30～15:30(L.O.15:00) 17:30～21:00(L.O.22:00) ",
			Regular_holiday: "木曜日",
			time_from_company: "8~10分",
		},
		{
			path: "/shop/8",
			name: "橙 ",
			address: "東京都目黒区大橋1-7-9 パークフラッツ中目黒 1F",
			genre: "中華",
			sub_genre: ["チャーハン", "中華料理"],
			photo: "",
			Recommended_number_of_people: "1~4人",
			business_hours: "11:30～15:30(L.O.15:00)",
			Regular_holiday: "年末年始",
			time_from_company: "8~10分",
		},
		{
			path: "/shop/9",
			name: "万豚記 池尻大橋店",
			address: "東京都目黒区東山3-13-3",
			genre: "中華",
			sub_genre: ["ラーメン", "餃子", "中華料理"],
			photo: "",
			Recommended_number_of_people: "1~4人",
			business_hours: "11:30 - 26:00（L.O.25:30）",
			Regular_holiday: "無休　※年末年始などを除く",
			time_from_company: "8~10分",
		},
		{
			path: "/shop/10",
			name: "シーメンハン 池尻大橋店 （C-MEN-HAN）",
			address: "東京都目黒区大橋2-24-4 ホテルサーブ渋谷 1F",
			genre: "中華",
			sub_genre: ["オムライス","中華料理", "小籠包"],
			photo: "",
			Recommended_number_of_people: "1~4人",
			business_hours: "11:30～17:00 17:00～23:30(L.O.23:00)",
			Regular_holiday: "無休",
			time_from_company: "10分",
		},
		{
			path: "/shop/11",
			name: "田燕 まるかく三 池尻大橋店",
			address: "東京都目黒区大橋2-22-8 いちご池尻ビル 1F",
			genre: "中華",
			sub_genre: ["中華料理", "居酒屋", "餃子"],
			photo: "",
			Recommended_number_of_people: "1~4人",
			business_hours: "11:30 - 15:00（14:30L.O.）",
			Regular_holiday: "無休",
			time_from_company: "5~8分",
		},
	];
};
